### PR TITLE
Hide notification messages

### PR DESCRIPTION
**Pull request by mgmacias95**
## What's new in this PR?

This PR adds backend support for https://github.com/wireapp/wire-android/issues/1924.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Can one of the admins verify this patch?

**Comment by marcoconti83** [comment]
ok to test

**Comment by marcoconti83** [comment]
add to whitelist

**Comment by marcoconti83** [comment]
build again

**Comment by marcoconti83** [comment]
Sorry for the noise, our build machine is misbehaving :)

**Pull request merged**
