### PR TITLE
feat: Enabled scoverage to get code coverage reports on CI

### PR DESCRIPTION
**Pull request by JPonte**

### CODE REVIEW

**Comment by JPonte** [comment]
build again

**Comment by JPonte** [comment]
build again

**Comment by JPonte** [comment]
build again

**Comment by JPonte** [comment]
build again

**Comment by JPonte** [comment]
build again

**Comment by JPonte** [comment]
build again

**Comment by JPonte** [comment]
build again

**Comment by marcoconti83** [comment]
Will this post codecov reports to PRs? The iOS team has something similar, if needed you can talk to @vytis on how they set it up.

**Comment by JPonte** [comment]
We have the webhook configured at least. We need to get the develop branch getting the coverage and then we can see if it is working as intended.

**Pull request merged**
