### PR TITLE
Simplified build configuration

### PR DESCRIPTION
**Pull request by vytis**
### Issues

There are several types of builds done in slightly different configurations and it could simplified to be more consistent. In addition the version numbers are set to different strings depending on Jenkins environment variables which makes it specific to the CI setup we have.

### Solutions

The table summarises the current situation. The proposed changes for version numbers are outlined

Branch | Version (current) | Version (proposed) | Debug | Bintray repo |
-- |	-- | -- | -- | -- | 
master | `141.0.512` | `141.0.512` | ❌ | Release
develop | `141.2237` | `141.0.512-DEV` | ✅ | Snapshot
PR | `141.768-PR` | `141.0.512-PR` | ✅ | Snapshot
Local | `141-SNAPSHOT` | `141.0.0-DEV` | ✅ | N/A

Also the way we build the project is changed slightly to make it less coupled to Jenkins:
* Passing the type of build as `Dbuild_type=dev` parameter. The value can be `dev`, `pr` or `release`. 
* Passing build number explicitly with `-Dbuild_number=123`. When it's not there (e.g. building locally) it will be set to `0`.

### Testing

Tried running tests with these parameters:
* `sbt -Dbuild_type=dev -Dbuild_number=123 test`
* `sbt -Dbuild_type=pr -Dbuild_number=123 test`
* `sbt -Dbuild_type=release -Dbuild_number=123 test`

## Questions

- [x] What would be a good way to fail build if `build_type` is not one of known values? It will default to `dev` build but this could be a user error.

### CODE REVIEW

**Comment by CalumMcCall** [comment]
Nice, I like this proposal. I've added a check and the build now fails if the build_type is invalid.

**Comment by marcoconti83** [comment]
The write-up is great 👍  
I don't understand if this replaces the `publishM2` command when developing locally? If yes, this PR should also update `README.md`.

**Comment by vytis** [comment]
I am not completely sure when `publishM2` is used exactly, but I think this should not make a difference. If you build without any parameters it will build a "Local" build from the table in the PR description.

**Comment by marcoconti83** [comment]
@vytis thanks for clarifying, then looks good to me

**Pull request merged**
