### PR TITLE
Add default rule for deriving LogShow instances.

### PR DESCRIPTION
**Pull request by yeryomenkom**
## What's new in this PR?

Default rule for deriving LogShow instances. We have a lot of cases where we use `LogShow.logShowWithHash`. I think that it safe enough to use it as a default type class instance.

### CODE REVIEW

**Comment by marcoconti83** [comment]
So if not specialized, a type that we try to log will fallback to be hashed? Does it mean that all types are now considered safe for logging (hashed)?

**Comment by marcoconti83** [comment]
@pwnsdx this PR is tweaking what is considered safe to log because it had become very cumbersome to explicitly allow every type.

**Comment by yeryomenkom** [comment]
> So if not specialized, a type that we try to log will fallback to be hashed? Does it mean that all types are now considered safe for logging (hashed)?

Yes.

**Comment by johnxnguyen** [comment]
@yeryomenkom I couldn't find any log show instances for primitive types. I thought it was intentional, but you may have forgotten to port them over to `LogShowInstancesSE`.

**Comment by johnxnguyen** [comment]
@yeryomenkom oh no still one test failed.

**Pull request merged**
